{
 "title": "Backend logs (loki)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"b2b\"} |= ``"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"b2b\"} |= `logged`"
    }
   ]
  },
  {
   "title": "WARNINGS",
   "type": "logs",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{app=\"b2b\"} |= `WARN`"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "{app=\"b2b\"} |= `ERROR`"
    }
   ]
  }
 ]
}