CREATE TABLE skills (
    id VARCHAR(255) PRIMARY KEY NOT NULL,
    parent_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    assignable BOOLEAN NOT NULL,
    image VARCHAR(255)
);

ALTER TABLE skills
ADD CONSTRAINT fk_parent_skills FOREIGN KEY (parent_id) REFERENCES skills(id);

INSERT INTO skills (id, name, parent_id, assignable, image) VALUES
('S1', 'Soft Skills', NULL, false, NULL),
('S2', 'Tech Skills', NULL, false, NULL),

('S3', 'Programming Languages', 'S2', false, NULL),
('S4', 'Front-End Frameworks', 'S2', false, NULL),
('S5', 'Back-End Frameworks', 'S2', false, NULL),
('S6', 'Test Tools', 'S2', false, NULL),
('S7', 'Database Systems', 'S2', false, NULL),
('S8', 'Project Management', 'S2', false, NULL),
('S9', 'Design', 'S2', false, NULL),
('S10', 'CMS/CMR', 'S2', true, NULL),
('S11', 'Cloud Platforms', 'S2', false, NULL),
('S12', 'CI/CD', 'S2', false, NULL),
('S13', 'Containerization and Orchestration', 'S2', false, NULL),
('S14', 'Data Visualization', 'S2', false, NULL),
('S15', 'Network and Security', 'S2', false, NULL),
('S16', 'Problem-Solving', 'S2', false, NULL),
('S17', 'Data Structures', 'S2', false, NULL),
('S18', 'Operating Systems', 'S2', false, NULL),
('S19', 'Scripting Languages', 'S2', false, NULL),
('S20', 'Git', 'S2', true, '/icons/Git.svg'),
('S21', 'JSON', 'S2', true, '/icons/JSON.svg'),
('S22', 'API Engines', 'S2', true, NULL),
('S23', 'Excel', 'S2', true, '/icons/Excel.svg'),
('S24', 'Spoken Languages', 'S2', false, NULL),
('S25', 'Markup Languages', 'S2', false, NULL),
('S26', 'Web Servers', 'S2', false, NULL),
('S27', 'Game Engines', 'S2', false, NULL),

('HS1', 'English', 'S24', true, NULL),
('HS2', 'Bulgarian', 'S24', true, NULL),
('HS3', 'German', 'S24', true, NULL),
('HS4', 'Spanish', 'S24', true, NULL),
('HS5', 'French', 'S24', true, NULL),
('HS6', 'Portuguese', 'S24', true, NULL),
('HS7', 'Chinese', 'S24', true, NULL),
('HS8', 'Japanese', 'S24', true, NULL),
('HS9', 'Korean', 'S24', true, NULL),

('SS1', 'Communication Skills', 'S1', true, NULL),
('SS2', 'Teamwork', 'S1', true, NULL),
('SS3', 'Problem Solving', 'S1', true, NULL),
('SS4', 'Adaptability', 'S1', true, NULL),
('SS5', 'Time Management', 'S1', true, NULL),

('PS1', 'Algorithms', 'S16', true, NULL),
('PS2', 'AI', 'S16', true, NULL),

('DS1', 'Queue', 'S17', true, NULL),
('DS2', 'Stack', 'S17', true, NULL),
('DS3', 'Tree', 'S17', true, NULL),
('DS4', 'LinkedList', 'S17', true, NULL),
('DS5', 'Array', 'S17', true, NULL),
('DS6', 'Graph', 'S17', true, NULL),
('DS7', 'HashMap', 'S17', true, NULL),

('T1', 'JavaScript', 'S3', true, '/icons/JavaScript.svg'),
('T2', 'HTML', 'S25', true, '/icons/HTML.svg'),
('T3', 'CSS', 'S3', true, '/icons/CSS3.svg'),
('T80', 'Tailwind CSS', 'T3', true, '/icons/Tailwind.svg'),
('T58', 'XML', 'S25', true, '/icons/XML.svg'),
('T4', 'TypeScript', 'S3', true, '/icons/TypeScript.svg'),
('T6', 'Java', 'S3', true, '/icons/Java.svg'),
('T8', 'Kotlin', 'S3', true, '/icons/Kotlin.svg'),
('T10', 'Swift', 'S3', true, '/icons/Swift.svg'),
('T11', 'Unity', 'S27', true, '/icons/Unity.svg'),
('T13', 'C++', 'S3', true, '/icons/CPlusPlus.svg'),
('T25', 'Python', 'S3', true, '/icons/Python.svg'),
('T30', 'SQL', 'S3', true, '/icons/SQL.svg'),
('T43', 'C#', 'S3', true, '/icons/CSharp.svg'),
('T44', 'PHP', 'S3', true, '/icons/PHP.svg'),
('T72', 'C', 'S3', true, '/icons/C.svg'),
('T73', 'Rust', 'S3', true, '/icons/Rust.svg'),
('T74', 'Go', 'S3', true, '/icons/Go.svg'),
('T77', 'GraphQL', 'S22', true, '/icons/GraphQL.svg'),
('T83', 'SCSS', 'T3', true, '/icons/CSS3.svg'),
('T84', 'Markdown', 'S25', true, '/icons/Markdown.svg'),
('T85', 'LaTeX', 'S25', true, '/icons/LaTeX.svg'),
('T86', 'MathML', 'S25', true, '/icons/MathML.png'),
('T87', 'Bootstrap', 'T3', true, '/icons/Bootstrap.svg'),
('T88', 'Sass', 'T3', true, '/icons/Sass.svg'),
('T90', 'Nginx', 'S26', true, '/icons/NGINX.svg'),
('T91', 'Apache HTTP Server', 'S26', true, '/icons/Apache.svg'),
('T93', 'Perl', 'S3', true, '/icons/Perl.svg'),
('T94', 'GitHub', 'S20', true, '/icons/GitHub.svg'),
('T95', 'GitLab', 'S20', true, '/icons/GitLab.svg'),
('T96', 'BitBucket', 'S20', true, '/icons/BitBucket.svg'),
('T100', 'Unreal Engine', 'S27', true, '/icons/UnrealEngine.svg'),
('T104', 'MaterialUI', 'T3', true, '/icons/MaterialUI.svg'),
('T51', 'Angular', 'S4', true, '/icons/AngularJS.svg'),
('T52', 'Vue', 'S4', true, '/icons/Vue.js.svg'),
('T5', 'React', 'S4', true, '/icons/React.svg'),
('T19', 'SwiftUI', 'S4', true, '/icons/SwiftUI.svg'),
('T29', 'Flutter', 'S4', true, '/icons/Flutter.svg'),
('T28', 'React Native', 'S4', true, '/icons/React.svg'),
('T102', 'Solid.js', 'S4', true, '/icons/Solid.js.svg'),
('T9', 'Material Design', 'S9', true, '/icons/MaterialUI.svg'),
('T7', 'Spring', 'S5', true, '/icons/Spring.svg'),
('T26', 'Django', 'S5', true, '/icons/Django.svg'),
('T27', 'Flask', 'S5', true, '/icons/Flask.svg'),
('T42', 'ASP.NET', 'S5', true, '/icons/ASP.NET.svg'),
('T53', ' .NET', 'S5', true, '/icons/NET.svg'),
('T75', 'Express.js', 'S5', true, '/icons/Express.svg'),
('T76', 'Node.js', 'S5', true, '/icons/Node.js.svg'),
('T78', 'Next.js', 'S5', true, '/icons/Next.js.svg'),
('T79', 'Nest.js', 'S5', true, '/icons/Nest.js.svg'),
('T81', 'Tauri', 'S5', true, '/icons/Tauri.svg'),
('T82', 'Fiber', 'S5', true, NULL),
('T14', 'Figma', 'S9', true, '/icons/Figma.svg'),
('T15', 'Adobe Photoshop', 'S9', true, '/icons/AdobePhotoshop.svg'),
('T16', 'Agile', 'S8', true, '/icons/Agile.png'),
('T17', 'Scrum', 'S8', true, '/icons/Scrum.svg'),
('T18', 'Jira', 'S8', true, '/icons/Jira.svg'),
('T97', 'Slack', 'S8', true, '/icons/Slack.svg'),
('T101', 'Trello', 'S8', true, '/icons/Trello.svg'),
('T20', 'LoadRunner', 'S6', true, '/icons/LoadRunner.png'),
('T21', 'Citrus', 'S6', true, '/icons/Citrus.png'),
('T22', 'Selenium', 'S6', true, '/icons/Selenium.svg'),
('T23', 'JUnit', 'S6', true, '/icons/JUnit.svg'),
('T24', 'TestNG', 'S6', true, NULL),
('T57', 'Postman', 'S6', true, '/icons/Postman.svg'),
('T65', 'Cypress', 'S6', true, '/icons/Cypress.svg'),
('T31', 'MongoDB', 'S7', true, '/icons/MongoDB.svg'),
('T62', 'PostgreSQL', 'S7', true, '/icons/PostgresSQL.svg'),
('T63', 'MySQL', 'S7', true, '/icons/MySQL.svg'),
('T66', 'Oracle Database', 'S7', true, '/icons/Oracle.svg'),
('T89', 'Apache Cassandra', 'S7', true, '/icons/ApacheCassandra.svg'),
('T92', 'MariaDB', 'S7', true, '/icons/MariaDB.svg'),
('T32', 'AWS', 'S11', true, '/icons/AWS.svg'),
('T33', 'Azure', 'S11', true, '/icons/Azure.svg'),
('T34', 'Google Cloud Platform', 'S11', true, '/icons/GoogleCloud.svg'),
('T35', 'Docker', 'S13', true, '/icons/Docker.svg'),
('T37', 'Kubernetes', 'S13', true, '/icons/Kubernetes.svg'),
('T70', 'Terraform', 'S13', true, '/icons/Terraform.svg'),
('T71', 'Prometheus', 'S13', true, '/icons/Prometheus.svg'),
('T36', 'Jenkins', 'S12', true, '/icons/Jenkins.svg'),
('T67', 'Maven', 'S12', true, '/icons/ApacheMaven.svg'),
('T45', 'WordPress', 'S10', true, '/icons/WordPress.svg'),
('T68', 'HubSpot', 'S10', true, '/icons/Hubspot.svg'),
('T69', 'Salesforce', 'S10', true, '/icons/Salesforce.svg'),
('T47', 'Wireshark', 'S15', true, '/icons/WireShark.svg'),
('T48', 'FileZilla', 'S15', true, '/icons/Filezilla.svg'),
('T49', 'VMWare', 'S15', true, '/icons/VMWare.svg'),
('T54', 'Linux', 'S18', true, '/icons/Linux.svg'),
('T55', 'Windows', 'S18', true, '/icons/Windows.svg'),
('T103', 'macOS', 'S18', true, '/icons/MacOS.svg'),
('T50', 'PowerBI', 'S14', true, '/icons/PowerBI.svg'),
('T41', 'Tableau', 'S14', true, '/icons/Tableau.svg'),
('T99', 'Grafana', 'S14', true, '/icons/Grafana.svg'),
('T60', 'PowerShell', 'S19', true, '/icons/PowerShell.svg'),
('T61', 'Bash', 'S19', true, '/icons/Bash.svg'),
('T64', 'Apache', 'S22', true, '/icons/Apache.svg'),
('T98', 'Swagger', 'S22', true, '/icons/Swagger.svg');