CREATE TABLE skills (
    id BIGSERIAL PRIMARY KEY,
    identifier VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    parent_id BIGINT,
    assignable BOOLEAN NOT NULL,
    image bytea,
    image_type VARCHAR(10)
);

ALTER TABLE skills
ADD CONSTRAINT fk_parent_skills FOREIGN KEY (parent_id) REFERENCES skills(id);

INSERT INTO skills (id, identifier, name, parent_id, assignable, image, image_type) VALUES
(1, 'S1', 'Soft Skills', NULL, false, NULL, NULL),
(2, 'S2', 'Tech Skills', NULL, false, NULL, NULL),

(3, 'S3', 'Programming Languages', 2, false, NULL, NULL),
(4, 'S4', 'Front-End Frameworks', 2, false, NULL, NULL),
(5, 'S5', 'Back-End Frameworks', 2, false, NULL, NULL),
(6, 'S6', 'Test Tools', 2, false, NULL, NULL),
(7, 'S7', 'Database Systems', 2, false, NULL, NULL),
(8, 'S8', 'Project Management', 2, false, NULL, NULL),
(9, 'S9', 'Design', 2, false, NULL, NULL),
(10, 'S10', 'CMS/CMR', 2, true, NULL, NULL),
(11, 'S11', 'Cloud Platforms', 2, false, NULL, NULL),
(12, 'S12', 'CI/CD', 2, false, NULL, NULL),
(13, 'S13', 'Containerization and Orchestration', 2, false, NULL, NULL),
(14, 'S14', 'Data Visualization', 2, false, NULL, NULL),
(15, 'S15', 'Network and Security', 2, false, NULL, NULL),
(16, 'S16', 'Problem-Solving', 2, false, NULL, NULL),
(17, 'S17', 'Data Structures', 2, false, NULL, NULL),
(18, 'S18', 'Operating Systems', 2, false, NULL, NULL),
(19, 'S19', 'Scripting Languages', 2, false, NULL, NULL),
(20, 'S20', 'Git', 2, true, pg_read_binary_file('/icons/Git.svg'), 'svg'),
(21, 'S21', 'JSON', 2, true, pg_read_binary_file('/icons/JSON.svg'), 'svg'),
(22, 'S22', 'API Engines', 2, true, NULL, NULL),
(23, 'S23', 'Excel', 2, true, pg_read_binary_file('/icons/Excel.svg'), 'svg'),
(24, 'S24', 'Spoken Languages', 2, false, NULL, NULL),
(25, 'S25', 'Markup Languages', 2, false, NULL, NULL),
(26, 'S26', 'Web Servers', 2, false, NULL, NULL),
(27, 'S27', 'Game Engines', 2, false, NULL, NULL),

(28 ,'HS1', 'English', 24, true, NULL, NULL),
(29 ,'HS2', 'Bulgarian', 24, true, NULL, NULL),
(30 ,'HS3', 'German', 24, true, NULL, NULL),
(31 ,'HS4', 'Spanish', 24, true, NULL, NULL),
(32 ,'HS5', 'French', 24, true, NULL, NULL),
(33 ,'HS6', 'Portuguese', 24, true, NULL, NULL),
(34 ,'HS7', 'Chinese', 24, true, NULL, NULL),
(35 ,'HS8', 'Japanese', 24, true, NULL, NULL),
(36 ,'HS9', 'Korean', 24, true, NULL, NULL),
 
(37 ,'SS1', 'Communication Skills', 1, true, NULL, NULL),
(38 ,'SS2', 'Teamwork', 1, true, NULL, NULL),
(39 ,'SS3', 'Problem Solving', 1, true, NULL, NULL),
(40 ,'SS4', 'Adaptability', 1, true, NULL, NULL),
(41 ,'SS5', 'Time Management', 1, true, NULL, NULL),

(42 ,'PS2', 'AI', 16, true, NULL, NULL),

(43 ,'DS1', 'Queue', 17, true, NULL, NULL),
(44 ,'DS2', 'Stack', 17, true, NULL, NULL),
(45 ,'DS3', 'Tree', 17, true, NULL, NULL),
(46 ,'DS4', 'LinkedList', 17, true, NULL, NULL),
(47 ,'DS5', 'Array', 17, true, NULL, NULL),
(48 ,'DS6', 'Graph', 17, true, NULL, NULL),
(49 ,'DS7', 'HashMap', 17, true, NULL, NULL),

(50 ,'T1', 'JavaScript', 3, true, pg_read_binary_file('/icons/JavaScript.svg'), 'svg'),
(51 ,'T2', 'HTML', 25, true, pg_read_binary_file('/icons/HTML.svg'), 'svg'),
(52 ,'T3', 'CSS', 3, true, pg_read_binary_file('/icons/CSS3.svg'), 'svg'),
(53 ,'T80', 'Tailwind CSS', 52, true, pg_read_binary_file('/icons/Tailwind.svg'), 'svg'),
(54 ,'T58', 'XML', 25, true, pg_read_binary_file('/icons/XML.svg'), 'svg'),
(55 ,'T4', 'TypeScript', 3, true, pg_read_binary_file('/icons/TypeScript.svg'), 'svg'),
(56 ,'T6', 'Java', 3, true, pg_read_binary_file('/icons/Java.svg'), 'svg'),
(57 ,'T8', 'Kotlin', 3, true, pg_read_binary_file('/icons/Kotlin.svg'), 'svg'),
(58 ,'T10', 'Swift', 3, true, pg_read_binary_file('/icons/Swift.svg'), 'svg'),
(59 ,'T11', 'Unity', 27, true, pg_read_binary_file('/icons/Unity.svg'), 'svg'),
(60 ,'T13', 'C++', 3, true, pg_read_binary_file('/icons/CPlusPlus.svg'), 'svg'),
(61 ,'T25', 'Python', 3, true, pg_read_binary_file('/icons/Python.svg'), 'svg'),
(62 ,'T30', 'SQL', 3, true, pg_read_binary_file('/icons/SQL.svg'), 'svg'),
(63 ,'T43', 'C#', 3, true, pg_read_binary_file('/icons/CSharp.svg'), 'svg'),
(64 ,'T44', 'PHP', 3, true, pg_read_binary_file('/icons/PHP.svg'), 'svg'),
(65 ,'T72', 'C', 3, true, pg_read_binary_file('/icons/C.svg'), 'svg'),
(66 ,'T73', 'Rust', 3, true, pg_read_binary_file('/icons/Rust.svg'), 'svg'),
(67 ,'T74', 'Go', 3, true, pg_read_binary_file('/icons/Go.svg'), 'svg'),
(68 ,'T77', 'GraphQL', 22, true, pg_read_binary_file('/icons/GraphQL.svg'), 'svg'),
(69 ,'T83', 'SCSS', 52, true, pg_read_binary_file('/icons/CSS3.svg'), 'svg'),
(70 ,'T84', 'Markdown', 25, true, pg_read_binary_file('/icons/Markdown.svg'), 'svg'),
(71 ,'T85', 'LaTeX', 25, true, pg_read_binary_file('/icons/LaTeX.svg'), 'svg'),
(72 ,'T86', 'MathML', 25, true, pg_read_binary_file('/icons/MathML.png'), 'png'),
(73 ,'T87', 'Bootstrap', 52, true, pg_read_binary_file('/icons/Bootstrap.svg'), 'svg'),
(74 ,'T88', 'Sass', 52, true, pg_read_binary_file('/icons/Sass.svg'), 'svg'),
(75 ,'T90', 'Nginx', 26, true, pg_read_binary_file('/icons/NGINX.svg'), 'svg'),
(76 ,'T91', 'Apache HTTP Server', 26, true, pg_read_binary_file('/icons/Apache.svg'), 'svg'),
(77 ,'T93', 'Perl', 3, true, pg_read_binary_file('/icons/Perl.svg'), 'svg'),
(78 ,'T94', 'GitHub', 20, true, pg_read_binary_file('/icons/GitHub.svg'), 'svg'),
(79 ,'T95', 'GitLab', 20, true, pg_read_binary_file('/icons/GitLab.svg'), 'svg'),
(80 ,'T96', 'BitBucket', 20, true, pg_read_binary_file('/icons/BitBucket.svg'), 'svg'),
(81 ,'T100', 'Unreal Engine', 27, true, pg_read_binary_file('/icons/UnrealEngine.svg'), 'svg'),
(82 ,'T104', 'MaterialUI', 52, true, pg_read_binary_file('/icons/MaterialUI.svg'), 'svg'),
(83 ,'T51', 'Angular', 4, true, pg_read_binary_file('/icons/AngularJS.svg'), 'svg'),
(84 ,'T52', 'Vue', 4, true, pg_read_binary_file('/icons/Vue.js.svg'), 'svg'),
(85 ,'T5', 'React', 4, true, pg_read_binary_file('/icons/React.svg'), 'svg'),
(86 ,'T19', 'SwiftUI', 4, true, pg_read_binary_file('/icons/SwiftUI.svg'), 'svg'),
(87 ,'T29', 'Flutter', 4, true, pg_read_binary_file('/icons/Flutter.svg'), 'svg'),
(88 ,'T28', 'React Native', 4, true, pg_read_binary_file('/icons/React.svg'), 'svg'),
(89 ,'T102', 'Solid.js', 4, true, pg_read_binary_file('/icons/Solid.js.svg'), 'svg'),
(90 ,'T9', 'Material Design', 9, true, pg_read_binary_file('/icons/MaterialUI.svg'), 'svg'),
(91 ,'T7', 'Spring', 5, true, pg_read_binary_file('/icons/Spring.svg'), 'svg'),
(92 ,'T26', 'Django', 5, true, pg_read_binary_file('/icons/Django.svg'), 'svg'),
(93 ,'T27', 'Flask', 5, true, pg_read_binary_file('/icons/Flask.svg'), 'svg'),
(94 ,'T42', 'ASP.NET', 5, true, pg_read_binary_file('/icons/ASP.NET.svg'), 'svg'),
(95 ,'T53', ' .NET', 5, true, pg_read_binary_file('/icons/NET.svg'), 'svg'),
(96 ,'T75', 'Express.js', 5, true, pg_read_binary_file('/icons/Express.svg'), 'svg'),
(97 ,'T76', 'Node.js', 5, true, pg_read_binary_file('/icons/Node.js.svg'), 'svg'),
(98 ,'T78', 'Next.js', 5, true, pg_read_binary_file('/icons/Next.js.svg'), 'svg'),
(99 ,'T79', 'Nest.js', 5, true, pg_read_binary_file('/icons/Nest.js.svg'), 'svg'),
(100 ,'T81', 'Tauri', 5, true, pg_read_binary_file('/icons/Tauri.svg'), 'svg'),
(101 ,'T82', 'Fiber', 5, true, NULL, NULL),
(102 ,'T14', 'Figma', 9, true, pg_read_binary_file('/icons/Figma.svg'), 'svg'),
(103 ,'T15', 'Adobe Photoshop', 9, true, pg_read_binary_file('/icons/AdobePhotoshop.svg'), 'svg'),
(104 ,'T16', 'Agile', 8, true, pg_read_binary_file('/icons/Agile.png'), 'png'),
(105 ,'T17', 'Scrum', 8, true, pg_read_binary_file('/icons/Scrum.svg'), 'svg'),
(106 ,'T18', 'Jira', 8, true, pg_read_binary_file('/icons/Jira.svg'), 'svg'),
(107 ,'T97', 'Slack', 8, true, pg_read_binary_file('/icons/Slack.svg'), 'svg'),
(108 ,'T101', 'Trello', 8, true, pg_read_binary_file('/icons/Trello.svg'), 'svg'),
(109 ,'T20', 'LoadRunner', 6, true, pg_read_binary_file('/icons/LoadRunner.png'), 'png'),
(110 ,'T21', 'Citrus', 6, true, pg_read_binary_file('/icons/Citrus.png'), 'png'),
(111 ,'T22', 'Selenium', 6, true, pg_read_binary_file('/icons/Selenium.svg'), 'svg'),
(112 ,'T23', 'JUnit', 6, true, pg_read_binary_file('/icons/JUnit.svg'), 'svg'),
(113 ,'T24', 'TestNG', 6, true, NULL, NULL),
(114 ,'T57', 'Postman', 6, true, pg_read_binary_file('/icons/Postman.svg'), 'svg'),
(115 ,'T65', 'Cypress', 6, true, pg_read_binary_file('/icons/Cypress.svg'), 'svg'),
(116 ,'T31', 'MongoDB', 7, true, pg_read_binary_file('/icons/MongoDB.svg'), 'svg'),
(117 ,'T62', 'PostgreSQL', 7, true, pg_read_binary_file('/icons/PostgresSQL.svg'), 'svg'),
(118 ,'T63', 'MySQL', 7, true, pg_read_binary_file('/icons/MySQL.svg'), 'svg'),
(119 ,'T66', 'Oracle Database', 7, true, pg_read_binary_file('/icons/Oracle.svg'), 'svg'),
(120 ,'T89', 'Apache Cassandra', 7, true, pg_read_binary_file('/icons/ApacheCassandra.svg'), 'svg'),
(121 ,'T92', 'MariaDB', 7, true, pg_read_binary_file('/icons/MariaDB.svg'), 'svg'),
(122 ,'T32', 'AWS', 11, true, pg_read_binary_file('/icons/AWS.svg'), 'svg'),
(123 ,'T33', 'Azure', 11, true, pg_read_binary_file('/icons/Azure.svg'), 'svg'),
(124 ,'T34', 'Google Cloud Platform', 11, true, pg_read_binary_file('/icons/GoogleCloud.svg'), 'svg'),
(125 ,'T35', 'Docker', 13, true, pg_read_binary_file('/icons/Docker.svg'), 'svg'),
(126 ,'T37', 'Kubernetes', 13, true, pg_read_binary_file('/icons/Kubernetes.svg'), 'svg'),
(127 ,'T70', 'Terraform', 13, true, pg_read_binary_file('/icons/Terraform.svg'), 'svg'),
(128 ,'T71', 'Prometheus', 13, true, pg_read_binary_file('/icons/Prometheus.svg'), 'svg'),
(129 ,'T36', 'Jenkins', 12, true, pg_read_binary_file('/icons/Jenkins.svg'), 'svg'),
(130 ,'T67', 'Maven', 12, true, pg_read_binary_file('/icons/ApacheMaven.svg'), 'svg'),
(131 ,'T45', 'WordPress', 10, true, pg_read_binary_file('/icons/WordPress.svg'), 'svg'),
(132 ,'T68', 'HubSpot', 10, true, pg_read_binary_file('/icons/Hubspot.svg'), 'svg'),
(133 ,'T69', 'Salesforce', 10, true, pg_read_binary_file('/icons/Salesforce.svg'), 'svg'),
(134 ,'T47', 'Wireshark', 15, true, pg_read_binary_file('/icons/WireShark.svg'), 'svg'),
(135 ,'T48', 'FileZilla', 15, true, pg_read_binary_file('/icons/Filezilla.svg'), 'svg'),
(136 ,'T49', 'VMWare', 15, true, pg_read_binary_file('/icons/VMWare.svg'), 'svg'),
(137 ,'T54', 'Linux', 18, true, pg_read_binary_file('/icons/Linux.svg'), 'svg'),
(138 ,'T55', 'Windows', 18, true, pg_read_binary_file('/icons/Windows.svg'), 'svg'),
(139 ,'T103', 'macOS', 18, true, pg_read_binary_file('/icons/MacOS.svg'), 'svg'),
(141 ,'T50', 'PowerBI', 14, true, pg_read_binary_file('/icons/PowerBI.svg'), 'svg'),
(142 ,'T41', 'Tableau', 14, true, pg_read_binary_file('/icons/Tableau.svg'), 'svg'),
(143 ,'T99', 'Grafana', 14, true, pg_read_binary_file('/icons/Grafana.svg'), 'svg'),
(144 ,'T60', 'PowerShell', 19, true, pg_read_binary_file('/icons/PowerShell.svg'), 'svg'),
(145 ,'T61', 'Bash', 19, true, pg_read_binary_file('/icons/Bash.svg'), 'svg'),
(146 ,'T64', 'Apache', 22, true, pg_read_binary_file('/icons/Apache.svg'), 'svg'),
(147 ,'T98', 'Swagger', 22, true, pg_read_binary_file('/icons/Swagger.svg'), 'svg'),
(148 ,'PS1', 'Algorithms', 16, true, NULL, NULL);