INSERT INTO domains (name) VALUES
('Cloud Computing'),
('Cybersecurity'),
('Data Analytics'),
('Artificial Intelligence (AI) and Machine Learning (ML)'),
('Internet of Things (IoT)'),
('Enterprise Software'),
('Blockchain'),
('IT Infrastructure and Networking'),
('DevOps and Software Development Tools'),
('Digital Transformation and Automation'),
('Business Intelligence (BI) and Analytics'),
('Augmented Reality (AR) and Virtual Reality (VR)'),
('Telecommunications and 5G Technology'),
('Digital Marketing and MarTech'),
('E-commerce Platforms and Payment Solutions'),
('Human Resources'),
('Digital Identity and Access Management'),
('Software Testing and Quality Assurance (QA)'),
('API Management and Integration');